"""Ajout de la colonne commentaire dans droits_plaidoirie

Revision ID: 1b7d0f699b12
Revises: a2b3c4d5e6f7
Create Date: 2025-08-28 13:05:20.729276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7d0f699b12'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.drop_column('commentaire')

    # ### end Alembic commands ###
