"""Ajout de ondelete cascade sur avocats.user_id

Revision ID: 4a094c863d0e
Revises: 357d4eb5cd13
Create Date: 2025-08-28 10:49:06.047863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a094c863d0e'
down_revision = '357d4eb5cd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avocats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('avocats_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avocats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('avocats_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
