"""MAJ table droit de plaidoirie

Revision ID: 55f913a41e07
Revises: 4a094c863d0e
Create Date: 2025-08-28 12:11:47.013567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f913a41e07'
down_revision = '4a094c863d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timbres_2500', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timbres_5000', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timbres_10000', sa.Integer(), nullable=True))
        batch_op.alter_column('agent_perception',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('droits_plaidoirie_avocat_id_fkey'), type_='foreignkey')
        batch_op.drop_column('avocat_id')
        batch_op.drop_column('nature_affaire')
        batch_op.drop_column('tribunal')
        batch_op.drop_column('numero_affaire')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_affaire', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tribunal', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nature_affaire', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avocat_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('droits_plaidoirie_avocat_id_fkey'), 'avocats', ['avocat_id'], ['avocat_id'])
        batch_op.alter_column('agent_perception',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('timbres_10000')
        batch_op.drop_column('timbres_5000')
        batch_op.drop_column('timbres_2500')

    # ### end Alembic commands ###
