"""Suppression de la relation entre un avocat et un droit de plaidoirie

Revision ID: 91d0163910e3
Revises: 55f913a41e07
Create Date: 2025-08-28 12:15:31.293402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91d0163910e3'
down_revision = '55f913a41e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.drop_column('date_validation')
        batch_op.drop_column('commentaire')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droits_plaidoirie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_validation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
