"""initial migration

Revision ID: 91e09ebf2851
Revises: 
Create Date: 2025-09-01 14:33:30.903189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e09ebf2851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets_avocat',
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cabinet_id')
    )
    op.create_table('fonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('batonnier', 'avocat', 'assistant_comptable', 'assistant_administratif', 'tresorier', 'secretaire', name='user_roles'), nullable=False),
    sa.Column('statut', sa.Enum('actif', 'inactif', 'suspendu', name='user_status'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('cree_par', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('avocats',
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('naissance', sa.Date(), nullable=False),
    sa.Column('sexe', sa.Enum('M', 'F', name='sexe_type'), nullable=False),
    sa.Column('d_serment', sa.Date(), nullable=True),
    sa.Column('d_inscription', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('actif', 'suspendu', 'radie', name='avocat_status'), nullable=True),
    sa.Column('qualification', sa.Enum('conseil_ordre', 'titulaire', 'stagiaire', name='qualification_type'), nullable=True),
    sa.Column('responsabilite_civile', sa.Text(), nullable=True),
    sa.Column('formation', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avocat_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('droits_plaidoirie',
    sa.Column('plaidoirie_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('timbres_2500', sa.Integer(), nullable=True),
    sa.Column('timbres_5000', sa.Integer(), nullable=True),
    sa.Column('timbres_10000', sa.Integer(), nullable=True),
    sa.Column('agent_perception', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('en_attente', 'valide', 'rejete', name='plaidoirie_status'), nullable=True),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_perception'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plaidoirie_id')
    )
    op.create_table('operations_fonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fond_id', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(length=200), nullable=True),
    sa.Column('motif', sa.String(length=200), nullable=True),
    sa.Column('fond_destination_id', sa.Integer(), nullable=True),
    sa.Column('date_reception', sa.Date(), nullable=True),
    sa.Column('date_depense', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validateur_id', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fond_destination_id'], ['fonds.id'], ),
    sa.ForeignKeyConstraint(['fond_id'], ['fonds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actes_avocat',
    sa.Column('acte_id', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.Column('date_acte', sa.Date(), nullable=False),
    sa.Column('date_depot', sa.Date(), nullable=False),
    sa.Column('numero_acte', sa.String(length=50), nullable=False),
    sa.Column('nature_acte', sa.String(length=200), nullable=False),
    sa.Column('identites_parties', sa.Text(), nullable=False),
    sa.Column('nombre_pages', sa.Integer(), nullable=False),
    sa.Column('agent_reception', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('recu', 'traite', 'archive', name='acte_status'), nullable=True),
    sa.ForeignKeyConstraint(['agent_reception'], ['users.id'], ),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.PrimaryKeyConstraint('acte_id'),
    sa.UniqueConstraint('numero_acte')
    )
    op.create_table('assistance_juridique',
    sa.Column('assistance_id', sa.Integer(), nullable=False),
    sa.Column('date_reception_demande', sa.Date(), nullable=False),
    sa.Column('date_demande', sa.Date(), nullable=False),
    sa.Column('numero_demande', sa.String(length=50), nullable=False),
    sa.Column('nature_demande', sa.String(length=200), nullable=False),
    sa.Column('nom_demandeur', sa.String(length=200), nullable=False),
    sa.Column('agent_reception', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=True),
    sa.Column('montant_alloue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('en_attente', 'assigne', 'en_cours', 'termine', 'annule', name='assistance_status'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_reception'], ['users.id'], ),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.PrimaryKeyConstraint('assistance_id'),
    sa.UniqueConstraint('numero_demande')
    )
    op.create_table('cabinet_membres',
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets_avocat.cabinet_id'], ),
    sa.PrimaryKeyConstraint('cabinet_id', 'avocat_id')
    )
    op.create_table('cotisations',
    sa.Column('cotisation_id', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.Column('annee_cotisation', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('d_echeance', sa.Date(), nullable=False),
    sa.Column('d_paiement', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('impaye', 'partiel', 'paye', 'en_retard', name='cotisation_status'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('reference_paiement', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.PrimaryKeyConstraint('cotisation_id')
    )
    op.create_table('formations',
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.Column('date_formation', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=False),
    sa.Column('titre_formation', sa.String(length=300), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('format_formation', sa.Enum('distantiel', 'presentiel', 'hybride', name='format_type'), nullable=False),
    sa.Column('organisateur', sa.String(length=200), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('certificat_obtenu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.PrimaryKeyConstraint('formation_id')
    )
    op.create_table('sanctions_disciplinaires',
    sa.Column('sanction_id', sa.Integer(), nullable=False),
    sa.Column('avocat_id', sa.Integer(), nullable=False),
    sa.Column('numero_decision', sa.String(length=50), nullable=False),
    sa.Column('date_sanction', sa.Date(), nullable=False),
    sa.Column('type_sanction', sa.Enum('avertissement', 'blame', 'suspension', 'radiation_temporaire', 'radiation_definitive', name='sanction_type'), nullable=False),
    sa.Column('motif_sanction', sa.Text(), nullable=False),
    sa.Column('duree_sanction', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('active', 'levee', 'expiree', name='sanction_status'), nullable=True),
    sa.Column('date_levee', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['avocat_id'], ['avocats.avocat_id'], ),
    sa.PrimaryKeyConstraint('sanction_id'),
    sa.UniqueConstraint('numero_decision')
    )
    op.create_table('acte_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acte_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_avocat.acte_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acte_documents')
    op.drop_table('sanctions_disciplinaires')
    op.drop_table('formations')
    op.drop_table('cotisations')
    op.drop_table('cabinet_membres')
    op.drop_table('assistance_juridique')
    op.drop_table('actes_avocat')
    op.drop_table('operations_fonds')
    op.drop_table('droits_plaidoirie')
    op.drop_table('avocats')
    op.drop_table('users')
    op.drop_table('fonds')
    op.drop_table('cabinets_avocat')
    # ### end Alembic commands ###
