"""Champs montant en integer au lieu de decimal

Revision ID: 9d3303990076
Revises: bbff896f32d7
Create Date: 2025-08-29 11:57:22.093310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3303990076'
down_revision = 'bbff896f32d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fonds', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('operations_fonds', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations_fonds', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('fonds', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
