"""Ajout des tables necessaires pour la gestion des fonds

Revision ID: bbff896f32d7
Revises: 1b7d0f699b12
Create Date: 2025-08-29 11:10:57.890695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbff896f32d7'
down_revision = '1b7d0f699b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('operations_fonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fond_id', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('provenance', sa.String(length=200), nullable=True),
    sa.Column('motif', sa.String(length=200), nullable=True),
    sa.Column('fond_destination_id', sa.Integer(), nullable=True),
    sa.Column('date_reception', sa.Date(), nullable=True),
    sa.Column('date_depense', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validateur_id', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fond_destination_id'], ['fonds.id'], ),
    sa.ForeignKeyConstraint(['fond_id'], ['fonds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations_fonds')
    op.drop_table('fonds')
    # ### end Alembic commands ###
